spawnAircraftAtAirfield("Lar", "JF-17", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Jiroft", "F-14A", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Tunb Island AFB", "Mirage F1EE", 4, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Bandar-e-Jask", "F-14A", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Khasab", "F-5E", 3, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Khasab", "MiG-21bis", 3, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Khasab", "Su-25T", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Qeshm Island", "MiG-21bis", 4, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Qeshm Island", "MiG-29S", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Qeshm Island", "Mirage F1EE", 4, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Qeshm Island", "Su-27", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Bandar Abbas", "Su-25T", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Bandar Abbas", "MiG-29S", 2, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Bandar Abbas", "Su-27", 4, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Bandar Abbas", "Mirage F1EE", 4, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Bandar Abbas", "MiG-21bis", 4, country.id.IRAN, coalition.side.RED)
spawnAircraftAtAirfield("Bandar Abbas", "F-5E", 4, country.id.IRAN, coalition.side.RED)
